# Generated by Chocoleotey. https://github.com/leobastiani/chocoleotey

$ErrorActionPreference = 'Stop';
$toolsDir = "$(Split-Path -parent $MyInvocation.MyCommand.Definition)"

Install-BinFile -Name 'datetime' -Path (Join-Path (Join-Path $toolsDir 'bin') 'datetime.bat')
